#!/usr/bin/env bash
# Generate edge Basic Auth gate WITHOUT secret env vars.
# (Netlify "secret" env in Edge Functions triggers team login redirect.)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
USER_NAME="${VUORO_BASIC_USER:-vuoro}"
PASS="${VUORO_SITE_PASSWORD:?VUORO_SITE_PASSWORD required}"
OUT="$ROOT/netlify/edge-functions/gate.js"
mkdir -p "$(dirname "$OUT")"

# Escape for JS string literals
js_escape() {
  python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$1"
}
USER_JS=$(js_escape "$USER_NAME")
PASS_JS=$(js_escape "$PASS")

cat > "$OUT" <<EOF
// Generated by scripts/gen-netlify-gate.sh — do not edit by hand.
export default async (request, context) => {
  const expectedUser = ${USER_JS};
  const expectedPass = ${PASS_JS};
  const header = request.headers.get("authorization") || "";
  if (!header.startsWith("Basic ")) {
    return new Response("Kirjautuminen vaaditaan — Vuoro", {
      status: 401,
      headers: {
        "WWW-Authenticate": 'Basic realm="Vuoro", charset="UTF-8"',
        "Cache-Control": "no-store",
        "Content-Type": "text/plain; charset=utf-8",
      },
    });
  }
  try {
    const decoded = atob(header.slice(6));
    const colon = decoded.indexOf(":");
    const user = colon >= 0 ? decoded.slice(0, colon) : "";
    const pass = colon >= 0 ? decoded.slice(colon + 1) : "";
    if (user === expectedUser && pass === expectedPass) {
      return context.next();
    }
  } catch (_) {}
  return new Response("Väärä tunnus tai salasana", {
    status: 401,
    headers: {
      "WWW-Authenticate": 'Basic realm="Vuoro", charset="UTF-8"',
      "Cache-Control": "no-store",
      "Content-Type": "text/plain; charset=utf-8",
    },
  });
};
export const config = { path: "/*" };
EOF

# Prefer .js over .ts so Netlify doesn't use the old TypeScript gate
rm -f "$ROOT/netlify/edge-functions/gate.ts"
echo "Wrote $OUT"
